spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    passsword:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

#logging:
#  level:
#    root: DEBUG