spring:
  profiles:
    default: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

rabbitmq:
  queues:
    person-register: person-register-queue
  listener:
    person-register:
      enabled: ${RABBITMQ_LISTENER_PERSON_REGISTER_ENABLED:true}
